# Generated by Django 4.2.7 on 2023-11-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("general", "Public"),
                            ("lecture", "Lecture"),
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                        ],
                        max_length=10,
                    ),
                ),
                ("meeting_location", models.CharField(max_length=200)),
                ("guest", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MeetingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="server.meeting",
                    ),
                ),
            ],
        ),
    ]
