# Generated by Django 4.2.7 on 2023-11-13 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meeting",
            old_name="date",
            new_name="meeting_date",
        ),
        migrations.RenameField(
            model_name="meeting",
            old_name="guest",
            new_name="meeting_guest",
        ),
        migrations.RenameField(
            model_name="meeting",
            old_name="title",
            new_name="meeting_title",
        ),
    ]
